# Install

In [ ]:
!pip3 install pshmodule

In [ ]:
!pip3 install pickle5

In [ ]:
!pip3 install pandas==1.5.0

In [ ]:
!pip3 install swifter

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Data Load

In [6]:
import sys
sys.path.append('drive/MyDrive/MemeProject/src/doc2vec/')
print(sys.path)

['/content', '/env/python', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.8/dist-packages/IPython/extensions', '/root/.ipython', 'drive/MyDrive/MemeProject/src/doc2vec/']

In [7]:
import config as cfg
from pshmodule.utils import filemanager as fm

In [8]:
df = fm.load(cfg.data_path_v1)

extension : .xlsx
Loaded 36602 records from drive/MyDrive/MemeProject//data/row_data/meme_v1.xlsx

In [9]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,총 세트 수,총 발화문 수,밈 제외 발화,밈 발화 수,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1525,24897,15747,9150,NaN,NaN,NaN
1,NaN,문장일련번호,관리번호,밈 id,set,utt,발화구분,대화소재,ARG0,발화문,ARG1,ARG_op,서술어,화행(U),meme_ID
2,NaN,1,Aa0001,DT0044,1,1,U,학교생활,나,나 중간고사 반에서 1등했어,중간고사,반에서,1등하다,자랑,NaN
3,NaN,2,NaN,NaN,NaN,2,U,학교생활,나,중간고사 점수 내가 반에서 제일 잘 받음,중간고사,반에서,점수 제일 잘 받다,자랑,NaN
4,NaN,3,NaN,NaN,NaN,3,U,학교생활,나,나 반에서 중간 성적 제일 좋아,중간,반에서,성적 제일 좋다,자랑,NaN

### create header

In [10]:
new_header = df.iloc[1]
df = df[2:]
df.columns = new_header

In [11]:
df.head()

1,NaN,문장일련번호,관리번호,밈 id,set,utt,발화구분,대화소재,ARG0,발화문,ARG1,ARG_op,서술어,화행(U),meme_ID
2,NaN,1,Aa0001,DT0044,1,1,U,학교생활,나,나 중간고사 반에서 1등했어,중간고사,반에서,1등하다,자랑,NaN
3,NaN,2,NaN,NaN,NaN,2,U,학교생활,나,중간고사 점수 내가 반에서 제일 잘 받음,중간고사,반에서,점수 제일 잘 받다,자랑,NaN
4,NaN,3,NaN,NaN,NaN,3,U,학교생활,나,나 반에서 중간 성적 제일 좋아,중간,반에서,성적 제일 좋다,자랑,NaN
5,NaN,4,NaN,NaN,NaN,4,U,학교생활,나,우리 반에서 내가 시험 제일 잘 봤다,시험,우리 반에서,제일 잘 보다,자랑,NaN
6,NaN,5,NaN,NaN,NaN,5,U,학교생활,NaN,중간고사 반 1등 먹음,중간고사,반,1등 먹다,자랑,NaN

# Merge V2

In [12]:
import pandas as pd

In [13]:
df2 = fm.load(cfg.data_path_v2)

extension : .xlsx
Loaded 14640 records from drive/MyDrive/MemeProject//data/row_data/meme_v2.xlsx

In [14]:
df2.head()

,문장일련번호,관리번호,밈 id,set,utt,발화구분,대화소재,ARG0,발화문,ARG1,ARG_op,서술어,화행(U),meme_ID
0,1,Aa0001,DT0044,1.0,1,U,학교생활,나,나 중간고사 반에서 1등했어,중간고사,NaN,반에서 1등하다,자랑,NaN
1,2,Aa0001,NaN,NaN,2,U,학교생활,나,중간고사 점수 내가 반에서 제일 잘 받음,중간고사,NaN,점수 반에서 제일 잘 받다,자랑,NaN
2,3,Aa0001,NaN,NaN,3,U,학교생활,나,나 반에서 중간 성적 제일 좋아,중간,NaN,반에서 성적 제일 좋다,자랑,NaN
3,4,Aa0001,NaN,NaN,4,U,학교생활,나,우리 반에서 내가 시험 제일 잘 봤다,시험,NaN,우리 반에서 제일 잘 보다,자랑,NaN
4,5,Aa0001,NaN,NaN,5,U,학교생활,NaN,중간고사 반 1등 먹음,중간고사,NaN,반 1등 먹다,자랑,NaN

In [15]:
df = pd.concat([df, df2])

In [16]:
df.shape

(51240, 15)

In [17]:
df.head()

,NaN,문장일련번호,관리번호,밈 id,set,utt,발화구분,대화소재,ARG0,발화문,ARG1,ARG_op,서술어,화행(U),meme_ID
2,NaN,1,Aa0001,DT0044,1,1,U,학교생활,나,나 중간고사 반에서 1등했어,중간고사,반에서,1등하다,자랑,NaN
3,NaN,2,NaN,NaN,NaN,2,U,학교생활,나,중간고사 점수 내가 반에서 제일 잘 받음,중간고사,반에서,점수 제일 잘 받다,자랑,NaN
4,NaN,3,NaN,NaN,NaN,3,U,학교생활,나,나 반에서 중간 성적 제일 좋아,중간,반에서,성적 제일 좋다,자랑,NaN
5,NaN,4,NaN,NaN,NaN,4,U,학교생활,나,우리 반에서 내가 시험 제일 잘 봤다,시험,우리 반에서,제일 잘 보다,자랑,NaN
6,NaN,5,NaN,NaN,NaN,5,U,학교생활,NaN,중간고사 반 1등 먹음,중간고사,반,1등 먹다,자랑,NaN

# column organize

In [18]:
df = df[['발화구분', '발화문', 'meme_ID']]

In [19]:
df.reset_index(inplace=True, drop=True)

In [20]:
df.head()

  발화구분                     발화문 meme_ID
0    U         나 중간고사 반에서 1등했어     NaN
1    U  중간고사 점수 내가 반에서 제일 잘 받음     NaN
2    U       나 반에서 중간 성적 제일 좋아     NaN
3    U    우리 반에서 내가 시험 제일 잘 봤다     NaN
4    U            중간고사 반 1등 먹음     NaN

In [21]:
df.rename(columns={'발화구분':'type', '발화문':'content', 'meme_ID':'meme_id'}, inplace=True)

In [22]:
df.shape

(51240, 3)

In [23]:
print(df.type.value_counts())
print("-"*100)
print(df.content.value_counts())
print("-"*100)
print(df.meme_id.value_counts())

U      12810
CPR    12810
MM     12810
CPO    12810
Name: type, dtype: int64
----------------------------------------------------------------------------------------------------
뭐야뭐야...👥👤👥 웅성웅성...👤👥👥👤    53
야 너두? 야 나두!               49
너... 뭐 돼...?              45
말을 잇지 못 하는...             43
또 나만 진심이었지...             43
                          ..
내일 걷기 가능?                  1
내일 기어다니는 거 아님?             1
내일 살아있기 가능?                1
끝나고 기절하는 거 아냐?             1
전국노래자랑에서 이모가 1등했다          1
Name: content, Length: 22651, dtype: int64
----------------------------------------------------------------------------------------------------
DT0044    42
ER0006    42
DT0029    42
DT0072    42
DT0121    42
          ..
AT0013    42
CR0010    42
ER0010    42
BT0006    42
DT0023    42
Name: meme_id, Length: 305, dtype: int64

#

# Serial to Parallel

#### 이모티콘에 대한 이슈
#### 중복 제거

### group numbering

In [24]:
num_li = []
number = 1

for k, v in enumerate(df.iterrows()):
    if k != 0 and k % 24 == 0:
        number += 1

    num_li.append(number)

In [25]:
df['group_no'] = num_li

### numbering

In [26]:
num_li = []
number = 1

for _ in df.iterrows():
    num_li.append(number)
    number += 1

In [27]:
num_li[:10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
df['num'] = num_li

In [29]:
df = df[['group_no', 'num', 'type', 'content']]

In [30]:
df.head(30)

    group_no  num type                     content
0          1    1    U             나 중간고사 반에서 1등했어
1          1    2    U      중간고사 점수 내가 반에서 제일 잘 받음
2          1    3    U           나 반에서 중간 성적 제일 좋아
3          1    4    U        우리 반에서 내가 시험 제일 잘 봤다
4          1    5    U                중간고사 반 1등 먹음
5          1    6    U              중간시험 내가 반 1등이야
6          1    7  CPR            그렇다면 통 크게 함 쏴야지!
7          1    8  CPR             ㄹㅇ? 대길이 한턱 쏴야겠네
8          1    9  CPR         1등 기념으로 플렉스 함 가즈아~!
9          1   10  CPR             진심? 그럼 자축하러 가야지
10         1   11  CPR           한턱 쏴 (짝) 한턱 쏴 (짝)
11         1   12  CPR                   1등턱 가나요~?
12         1   13   MM           근데 이제 내 것도 곁들인...
13         1   14   MM     근데 이제 내 몫을 제일 많이 곁들인...
14         1   15   MM         근데 이제 대춘이 몫도 곁들인...
15         1   16   MM  근데 이제 배보다 배꼽이 더 큰 걸 곁들인...
16         1   17   MM           근데 이제 과소비를 곁들인...
17         1   18   MM            근데 이제 탕진을 곁들인...
18         1   19  CPO                         NaN
19         1   20  CPO                         NaN
20         1   21  CPO                         NaN
21         1   22  CPO                         NaN
22         1   23  CPO                         NaN
23         1   24  CPO                         NaN
24         2   25    U               너 왜 이렇게 멍청하냐?
25         2   26    U                이 새끼 빡대가리잖아?
26         2   27    U                너 말귀 못 알아듣냐고
27         2   28    U                  병신 이해력 딸리네
28         2   29    U                   대가리는 장식임?
29         2   30    U                      얘 밥통이네

### work to parallelize

In [31]:
from tqdm import tqdm
import pandas as pd

In [32]:
content_li = []
cpr_li = []
mm_li = []
cpo_li = []


for i in tqdm(range(max(df.group_no))):
    df_temp = df[df.group_no==i+1]
    
    # type U
    df_temp_u = df_temp[df_temp.type=='U']
    df_temp_u.reset_index(inplace=True, drop=True)
    for k in range(6):
        for _ in range(216):
            content_li.append(df_temp_u.content.iloc[k])

    # type CPR
    df_temp_cpr = df_temp[df_temp.type=='CPR']
    df_temp_cpr.reset_index(inplace=True, drop=True)
    for _ in range(6):
        for k in range(6):
            for _ in range(36):
                cpr_li.append(df_temp_cpr.content.iloc[k])
                
    # type MM
    df_temp_mm = df_temp[df_temp.type=='MM']
    df_temp_mm.reset_index(inplace=True, drop=True)
    for _ in range(6):
        for _ in range(6):
            for k in range(6):
                for _ in range(6):
                    mm_li.append(df_temp_mm.content.iloc[k])

    # type CPO
    df_temp_cpo = df_temp[df_temp.type=='CPO']
    df_temp_cpo.reset_index(inplace=True, drop=True)
    for _ in range(6):
        for _ in range(6):
            for _ in range(6):
                for k in range(6):
                        cpo_li.append(df_temp_cpo.content.iloc[k])

100%|██████████| 2135/2135 [02:39<00:00, 13.38it/s]

In [33]:
df_result = pd.DataFrame([x for x in zip(content_li, cpr_li, mm_li, cpo_li)], columns=['u', 'cpr', 'mm', 'cpo'])

In [34]:
df_result.shape

(2766960, 4)

In [35]:
df_result.head()

                 u               cpr                 mm  cpo
0  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!  근데 이제 내 것도 곁들인...  NaN
1  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!  근데 이제 내 것도 곁들인...  NaN
2  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!  근데 이제 내 것도 곁들인...  NaN
3  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!  근데 이제 내 것도 곁들인...  NaN
4  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!  근데 이제 내 것도 곁들인...  NaN

### drop duplicate

In [36]:
df_result.drop_duplicates(inplace=True)

In [37]:
df_result.reset_index(inplace=True, drop=True)

In [38]:
df_result.shape

(208700, 4)

In [39]:
df_result.head()

                 u               cpr                          mm  cpo
0  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!           근데 이제 내 것도 곁들인...  NaN
1  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!     근데 이제 내 몫을 제일 많이 곁들인...  NaN
2  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!         근데 이제 대춘이 몫도 곁들인...  NaN
3  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!  근데 이제 배보다 배꼽이 더 큰 걸 곁들인...  NaN
4  나 중간고사 반에서 1등했어  그렇다면 통 크게 함 쏴야지!           근데 이제 과소비를 곁들인...  NaN

In [40]:
df_temp = df_result[df_result['u']=='5252 나 말이야 서른 되기 전에 스웨덴으로 여행갈 거다']

In [41]:
df_temp.head()

Empty DataFrame
Columns: [u, cpr, mm, cpo]
Index: []

# Save

In [ ]:
fm.save(cfg.temp_ref_data_colab, df_result)

Saved 208700 records